id: P000660
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16945
  title: དབྱངས་ཅན་ངག་གི་འགྱུར་ཁུག
  author: ''
  volumes:
    a520dfa1576447aa9e7f16ed9bbe6e64:
      image_group_id: I1KG18203
      title: ''
      volume_number: 1
      total_pages: 266
