id: P000660
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 15:57:49.700811
source_metadata:
  id: bdr:W1KG16945
  title: དབྱངས་ཅན་ངག་གི་འགྱུར་ཁུག
  author: ''
  volumes:
    a520dfa1576447aa9e7f16ed9bbe6e64:
      image_group_id: I1KG18203
      title: ''
      volume_number: 1
      total_pages: 266
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
